import axios, { AxiosError, AxiosResponse } from 'axios';

/**
 * Resolve the API base URL at runtime.
 *
 * Reads API_PORT from window.__RUNTIME_CONFIG__ (generated by start.sh
 * from config.yaml), then combines it with the browser's current hostname.
 * This way remote access (e.g. http://10.210.156.69:16888) automatically
 * talks to http://10.210.156.69:16889 — no .env or compile-time vars needed.
 */
function resolveApiBaseUrl(): string {
  const runtimeConfig = (window as any).__RUNTIME_CONFIG__ || {};
  const apiPort = runtimeConfig.API_PORT || 16889;
  const protocol = window.location.protocol; // http: or https:
  const hostname = window.location.hostname || 'localhost';
  return `${protocol}//${hostname}:${apiPort}`;
}

axios.defaults.baseURL = resolveApiBaseUrl();
axios.defaults.withCredentials = false;

console.log('[GraphRAG] API base URL:', axios.defaults.baseURL);

const responseBody = (response: AxiosResponse) => response.data;

axios.interceptors.response.use(
  async (response) => response,
  (error: AxiosError<any, any>) => {
    if (!error.response) {
      console.error('Network error: Server may be down');
      return Promise.reject(error);
    }
    const { data, status } = error.response;
    switch (status) {
      case 400:
        if (data.errors) {
          const modelStateErrors: string[] = [];
          for (const key in data.errors) {
            if (data.errors[key]) {
              modelStateErrors.push(data.errors[key]);
            }
          }
          console.error('Validation errors:', modelStateErrors.flat());
        } else {
          console.error('Bad request:', data.title);
        }
        break;
      case 401:
        console.error('Unauthorized:', data.title || 'Unauthorized');
        break;
      case 403:
        console.error('Forbidden: You are not allowed to do that!');
        break;
      case 500:
        console.error('Server Error:', data.title || 'Server Error!');
        break;
      default:
        console.error('An unexpected error occurred.');
        break;
    }
    return Promise.reject(error.response);
  }
);

const requests = {
  get: (url: string, params?: URLSearchParams) =>
    axios.get(url, { params }).then(responseBody),
  post: (url: string, body?: {}, params?: URLSearchParams) =>
    axios.post(url, body, { params }).then(responseBody),
  put: (url: string, body: {}) => axios.put(url, body).then(responseBody),
  delete: (url: string) => axios.delete(url).then(responseBody),
  getBlob: (url: string) =>
    axios.get(url, { responseType: 'arraybuffer' }).then((res) => res.data as ArrayBuffer),
};

export interface DataSourceInfo {
  name: string;
  path: string;
  description: string;
  active: boolean;
}

const Search = {
  global: (query: string) => requests.get('search/global', new URLSearchParams({ query })),
  local: (query: string) => requests.get('search/local', new URLSearchParams({ query })),
  drift: (query: string) => requests.get('search/drift', new URLSearchParams({ query })),
  basic: (query: string) => requests.get('search/basic', new URLSearchParams({ query })),
};

const DataSources = {
  list: (): Promise<{ data_sources: DataSourceInfo[] }> => requests.get('api/datasources'),
  switch: (name: string) => requests.post('api/datasources/switch', undefined, new URLSearchParams({ name })),
  current: (): Promise<{ current_source: string }> => requests.get('api/datasources/current'),
  listParquetFiles: (): Promise<{ files: string[] }> => requests.get(`api/parquet?_t=${Date.now()}`),
  getParquetFile: (filename: string, cacheBuster?: number): Promise<ArrayBuffer> =>
    requests.getBlob(`api/parquet/${filename}${cacheBuster ? `?_t=${cacheBuster}` : ''}`),
};

const Status = {
  check: () => requests.get('status'),
};

const Config = {
  get: () => requests.get('api/config'),
};

const agent = {
  Search,
  DataSources,
  Status,
  Config,
};

export default agent;
